// <auto-generated />
using BackEnd.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240515204621_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.Domain.Models.Debtors.Debtor", b =>
                {
                    b.Property<int>("DebtorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DebtorId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AssessedIncome")
                        .HasColumnType("int");

                    b.Property<int>("BalanceOfDebt")
                        .HasColumnType("int");

                    b.Property<bool>("Complaints")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DebtorId");

                    b.ToTable("Debtors");

                    b.HasData(
                        new
                        {
                            DebtorId = 1,
                            Address = "09 Westend Terrace",
                            AssessedIncome = 60668,
                            BalanceOfDebt = 11585,
                            Complaints = true,
                            FirstName = "Supun",
                            LastName = "Priyamantha",
                            SSN = "424-11-9327"
                        },
                        new
                        {
                            DebtorId = 2,
                            Address = "04 Eastend Terrace",
                            AssessedIncome = 78968,
                            BalanceOfDebt = 11543,
                            Complaints = true,
                            FirstName = "Sandun",
                            LastName = "Lasantha",
                            SSN = "424-11-9323"
                        },
                        new
                        {
                            DebtorId = 3,
                            Address = "04 North London",
                            AssessedIncome = 85245,
                            BalanceOfDebt = 10258,
                            Complaints = false,
                            FirstName = "Kasun",
                            LastName = "Shanaka",
                            SSN = "424-11-4717"
                        },
                        new
                        {
                            DebtorId = 4,
                            Address = "04 North Wellington",
                            AssessedIncome = 96587,
                            BalanceOfDebt = 20147,
                            Complaints = true,
                            FirstName = "Roy",
                            LastName = "Dias",
                            SSN = "424-12-7896"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
